<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo" failures="1" tests="4" name="Test" time="0.232" errors="0" timestamp="2024-09-25T08:54:09 IST">
  <testcase classname="test.TestNGUnitTestCases" name="test1" time="0.012"/>
  <testcase classname="test.TestNGUnitTestCases" name="test2" time="0.008"/>
  <testcase classname="test.TestNGUnitTestCases" name="test3" time="0.061">
    <failure type="java.lang.AssertionError" message="This is Test NG Unit test case is Fail expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: This is Test NG Unit test case is Fail expected [false] but found [true]
at test.TestNGUnitTestCases.test3(TestNGUnitTestCases.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="test.TestNGUnitTestCases" name="test4" time="0.005"/>
</testsuite> <!-- Test -->
